### ISSUE TITLE
Does this uastring apply to all users?  Should it be set up to be adjustable?

### ISSUE THREAD

**Issue by bbrewington** [corynissen/yahooFantasySports#1]
uastring <- "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36"

**Comment by corynissen** [comment]
As long as it works... it doesn't much matter what it is. The default rvest one doesn't work.

**Comment by bbrewington** [comment]
True.  I've been using it now the way it is and it works fine.
